### PR TITLE
improve clarity of setup and output

### PR DESCRIPTION
**Pull request by brandonopened**
- Added notes about resolving go package dependencies and local docker container
- output now sorts by relevance highest to lowest

### CODE REVIEW

**Comment by adamblum** [comment]
low numbers are better than high numbers. It sorts by "distance"

**Comment by brandonopened** [comment]
Exactly - so this sorts the lower numbers = better or even exact matches at the top of the sheet. Minor usability enhancement.

**Comment by adamblum** [comment]
hmm, I had made that change already (quite some time ago).

**Comment by adamblum** [comment]
GMTA as I had already changed .gitignore as well. the go get thing is just part of go ecosystem standard practice, not appropriate for comments.  I appreciate the pull request though

**Comment by brandonopened** [comment]
ok thanks, closing PR then.

**Comment by adamblum** [comment]
I am incorporating your feedback about troubleshooting ports though!

**Pull request closed without merging**
